# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstAppMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirstAppMVVM
  pod 'Alamofire'
end
